FilmProjesi/Controllers/FilmsController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using Microsoft.AspNetCore.Mvc;

namespace FilmProjesi.Controllers
{
    public class FilmsController : Controller
    {
        VideosManager vm = new VideosManager(new EfVideosRepository());
        CategoryManager cm = new CategoryManager(new EfCategoryRepository());
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Details(int id)
        {
            var result = vm.TGetById(id);
            return View(result);
        }
        public IActionResult CategoryList(int id)
        {
            var result = vm.GetList(x => x.CategoryId == id);
            if(result==null)
            {
                return RedirectToAction("Index","Home");
            }
            return View(result);

        }
    }
}

FilmProjesi/Views/Shared/Components/FeaturedList/Default.cshtml
@model List<EntityLayer.Concrete.Videos>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <p>Değerli Arı Film Cehenemi Ailesi <span><a href="">Buradan İndir</a></span></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h2>Öne Çıkan Filmler</h2>
        </div>
    </div>
    <div class="row">
        
        @foreach(var item in Model)
        {
            <div class="col-3 text-center border">
                <img src="@(
              item.Picture == null
              ? "Film_Images/resim_yok.png"
               : "Film_Images/" + item.Picture
              )   
                " class="img-fluid border mt-2">
                <h4>@item.Title</h4>
                <p>@item.CategoryId</p>
                <a asp-action="Details" asp-controller="Films" asp-route-id="@item.VideoId" class="btn btn-primary mb-2">Film İzle</a>

            </div>
        }
       
    
       
       

    </div>

</div>