FilmProjesi/Controllers/CategoryApiController.cs
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;

namespace FilmProjesi.Controllers
{
    public class CategoryApiController : Controller
    {
        Uri baseAddress = new Uri("https://localhost:7121/api");
        //kullanacağımz api yolu alıyorum baseAdress buradan çekiyorum
        private readonly HttpClient _client;
        /// <summary>
        /// istemci oluşturuyorum.
        /// </summary>
        public CategoryApiController()
        {
          
            _client = new HttpClient();
            _client.BaseAddress = baseAddress;
        }
        [HttpGet]
        public IActionResult Index()
        {
            List<Category> categories = new List<Category>();
            //bir liste oluştur categori listesi olacak
            HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Category/").Result;
            //getAsnc metodu ile veri çek _clientBaseAddress http://localhost:7121/api
            if(response.IsSuccessStatusCode)
            {
                //response.IsSuccessStatusCode 200
                string data=response.Content.ReadAsStringAsync().Result;
                //gelen veri ReadAstring olarak oku ve data at
                categories=JsonConvert.DeserializeObject<List<Category>>(data);
                // veri formatına çevir json verisini veri çevirdik
            }
          
            return View(categories);
        }
        [HttpGet]
        public IActionResult Create()
        { 
           return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Category category)
        {
            try
            {
               string data=JsonConvert.SerializeObject(category);
                //gelen veriyi al json formatın çevir
               StringContent content=new StringContent(data,Encoding.UTF8,"Application/Json");

                //data içerisine json verisinin utf-8 biçiinde olacağın yazıyoruz.
                HttpResponseMessage response = _client.PostAsync(_client.BaseAddress + "/Category/",content).Result;

                if(response.IsSuccessStatusCode) {
                    return RedirectToAction("Index");
                }
            }
            catch(Exception ex)
            {
                TempData["Error"] = ex;
                return View();
            }
            return View(category);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {

            try
            {
                Category category = new Category();
                HttpResponseMessage response = await _client.GetAsync(_client.BaseAddress + "/Category/Get" + id);

                if (response.IsSuccessStatusCode)
                {
                    string data = await response.Content.ReadAsStringAsync();
                    category = JsonConvert.DeserializeObject<Category>(data);
                    return View(category);
                }
                else
                {
                    // Hata durumunu işlemek için buraya ekleme yapın
                    return View("Error");
                }
            }
            catch(Exception ex)
            {
                TempData["Error"] = ex;
                return View();
            }
            return View();
        }
        [HttpPost]
        public IActionResult Delete(int id, Category category)
        {
            try
            {
                HttpResponseMessage response = _client.DeleteAsync(_client.BaseAddress + "/Category/" + id).Result;
                if(response.IsSuccessStatusCode)
                {
                    TempData["Success"] = "İşlem Başarılı";
                    return RedirectToAction("index");
                }
            }
            catch(Exception ex)
            {
                TempData["Error"] = "Hata Oluştu";
                return View();
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {

            try
            {
                Category category = new Category();
                HttpResponseMessage response = await _client.GetAsync($"{_client.BaseAddress}/Category/Get/{id}");
                if (response.IsSuccessStatusCode)
                {
                    string data =await response.Content.ReadAsStringAsync();
                    category = JsonConvert.DeserializeObject<Category>(data);
                    return View(category);
                }
            }
            catch(Exception ex)
            {
                TempData["Error"] = ex;
                return View();  
            }
            return View();



           

           
        }
        [HttpPost]
        public IActionResult Edit(int id,Category category)
        {
            try
            {
                string data=JsonConvert.SerializeObject(category);
                StringContent content=new StringContent(data,Encoding.UTF8,"Application/Json");
                HttpResponseMessage response = _client.PutAsync(_client.BaseAddress + "/Category/", content).Result;
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }

            }
            catch(Exception ex)
            {
                TempData["Error"] = ex;
                return View();
            }
            return View();
        }
    }
}

FilmProjesi/Controllers/CategoryController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace FilmProjesi.Controllers
{
    public class CategoryController : Controller
    {
     CategoryManager categoryManager = new CategoryManager(new EfCategoryRepository());
        public IActionResult Index()
        {
           var result= categoryManager.GetAll();
            return View(result);
        }
        [HttpGet]
        public IActionResult Create() 
        {
           return View();
        }
        [HttpPost]  
        public IActionResult Create(Category entity)
        {
            categoryManager.TAdd(entity);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var result=categoryManager.TGetById(id);
            return View(result);
        }
        [HttpPost]  
        public IActionResult Edit(Category entity)
        {
            categoryManager.TUpdate(entity);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
          var result =categoryManager.TGetById(id);
            return View(result);
        
        }
        [HttpPost]
        public IActionResult Delete(Category entity)
        {
            categoryManager.TRemove(entity);
            return RedirectToAction("Index");
        }
    }
}

FilmProjesi/Views/CategoryApi/Create.cshtml
@model EntityLayer.Concrete.Category
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<form asp-action="Create" asp-controller="CategoryApi">
    <div class="form-group">
        <label for="exampleInputEmail1">Kategori Adı</label>
        <input type="text" class="form-control" name="CategoryName" placeholder="Kategori Adı">

    </div>


    <button type="submit" class="btn btn-primary">Submit</button>
</form>

FilmProjesi/Views/CategoryApi/Delete.cshtml
@model EntityLayer.Concrete.Category
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<form asp-action="Delete" asp-controller="CategoryApi">
    <div class="form-group">
        <label for="exampleInputEmail1">Kategori Adı</label>
        <input readonly type="text" class="form-control" name="CategoryName" asp-for="CategoryName" placeholder="Kategori Adı">
        <input type="hidden" asp-for="CategoryId" name="CategoryId" />
    </div>


    <button type="submit" class="btn btn-primary">Silmek İstiyorum</button>
    <a class="btn btn-dark" asp-action="Index" asp-controller="Category">İptal</a>

</form>

FilmProjesi/Views/CategoryApi/Edit.cshtml
@model EntityLayer.Concrete.Category
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<form asp-action="Edit" asp-controller="CategoryApi">
    <div class="form-group">
        <label for="exampleInputEmail1">Kategori Adı</label>
        <input type="text" class="form-control" name="CategoryName" asp-for="CategoryName" placeholder="Kategori Adı">
        <input type="hidden" asp-for="CategoryId" name="CategoryId" />
    </div>


    <button type="submit" class="btn btn-primary">Submit</button>
</form>

FilmProjesi/Views/CategoryApi/Index.cshtml
@model List<EntityLayer.Concrete.Category>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<h1>Index</h1>
<a class="btn btn-warning" asp-action="Create">Yeni Kayıt</a>
<div class="row">
    <div class="col-md-12">
        <div class="white_shd full margin_bottom_30">
            <div class="full graph_head">
                <div class="heading1 margin_0">
                    <h2>Kategoriler</h2>
                </div>
            </div>
            <div class="table_section padding_infor_info">
                <div class="table-responsive-sm">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Kategori Adı</th>
                                <th>Düzeltme</th>
                                <th>Silme</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.CategoryName</td>
                                    <td><a class="btn btn-success" asp-action="Edit" asp-route-id="@item.CategoryId">Düzelt</a></td>
                                    <td><a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.CategoryId">Silme</a></td>
                                </tr>
                            }


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


</div>