FilmProjesi/Controllers/VideosController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace FilmProjesi.Controllers
{
    public class VideosController : Controller
    {
        
        VideosManager vm = new VideosManager(new EfVideosRepository());
        public IActionResult Index()
        {
            var result = vm.GetAll();
            return View(result);
           
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Videos entity)
        {
            vm.TAdd(entity);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var result=vm.TGetById(id);
            return View(result);
        }
        [HttpPost]
        public IActionResult Edit(Videos entity)
        {
            vm.TUpdate(entity);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            var result = vm.TGetById(id);
            return View(result);
        }
        [HttpPost]
        public IActionResult Delete(Videos entity)
        {
            vm.TRemove(entity);
            return RedirectToAction("Index");
        }
    }
}

FilmProjesi/Views/Videos/Create.cshtml
@model EntityLayer.Concrete.Videos
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<form asp-action="Create" asp-controller="Videos">
    <div class="form-group">
        <label for="exampleInputEmail1">Film Adı</label>
        <input type="text" class="form-control" asp-for="Title" name="Title"   placeholder="Kategori Adı">
       
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Açıklaması</label>
        <input type="text" class="form-control" asp-for="Description" name="Description" placeholder="Kategori Adı">

    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Kategorisi</label>
        <input type="text" class="form-control" asp-for="CategoryId" name="CategoryId" placeholder="Kategori Adı">

    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Yılı</label>
        <input type="text" class="form-control" asp-for="Year" name="Year" placeholder="Kategori Adı">

    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Ülkesi</label>
        <input type="text" class="form-control" asp-for="Country" name="Country" placeholder="Kategori Adı">

    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Video Resim</label>
        <input type="text" class="form-control" asp-for="Picture" name="Picture" placeholder="Kategori Adı">

    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Film Videosu</label>
        <input type="text" class="form-control" asp-for="Film" name="Film" placeholder="Kategori Adı">

    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Aktörler</label>
        <input type="text" class="form-control" asp-for="Actors" name="Actors" placeholder="Kategori Adı">

    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Yönetmen</label>
        <input type="text" class="form-control" asp-for="Director" name="Director" placeholder="Kategori Adı">

    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Fragman</label>
        <input type="text" class="form-control" asp-for="Teaser" name="Teaser" placeholder="Kategori Adı">

    </div>
  
   
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

FilmProjesi/Views/Videos/Delete.cshtml
@model EntityLayer.Concrete.Videos
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<form asp-action="Delete" asp-controller="Videos">
    <div class="form-group">
        <input type="hidden" name="VideoId" asp-for="VideoId"/>
        <label for="exampleInputEmail1">Film Adı</label>
        <input type="text" readonly class="form-control" asp-for="Title" name="Title"   placeholder="Kategori Adı">
       
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Açıklaması</label>
        <input type="text" readonly class="form-control" asp-for="Description" name="Description" placeholder="Kategori Adı">

    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Kategorisi</label>
        <input type="text" readonly class="form-control" asp-for="CategoryId" name="CategoryId" placeholder="Kategori Adı">

    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Yılı</label>
        <input type="text" readonly class="form-control" asp-for="Year" name="Year" placeholder="Kategori Adı">

    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Ülkesi</label>
        <input type="text" readonly class="form-control" asp-for="Country" name="Country" placeholder="Kategori Adı">

    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Video Resim</label>
        <input type="text" readonly class="form-control" asp-for="Picture" name="Picture" placeholder="Kategori Adı">

    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Film Videosu</label>
        <input type="text" readonly class="form-control" asp-for="Film" name="Film" placeholder="Kategori Adı">

    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Aktörler</label>
        <input type="text" readonly class="form-control" asp-for="Actors" name="Actors" placeholder="Kategori Adı">

    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Yönetmen</label>
        <input type="text" readonly class="form-control" asp-for="Director" name="Director" placeholder="Kategori Adı">

    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Fragman</label>
        <input type="text" readonly class="form-control" asp-for="Teaser" name="Teaser" placeholder="Kategori Adı">

    </div>
  
   
    <button type="submit" class="btn btn-primary">Bu Kayıt Silinecek</button>
    <a asp-action="index" class="btn btn-secondary" asp-controller="Videos">İşlemi İptal Et</a>
</form>

FilmProjesi/Views/Videos/Edit.cshtml
@model EntityLayer.Concrete.Videos
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<form asp-action="Edit" asp-controller="Videos">
    <div class="form-group">
        <input type="hidden" name="VideoId" asp-for="VideoId"/>
        <label for="exampleInputEmail1">Film Adı</label>
        <input type="text" class="form-control" asp-for="Title" name="Title"   placeholder="Kategori Adı">
       
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Açıklaması</label>
        <input type="text" class="form-control" asp-for="Description" name="Description" placeholder="Kategori Adı">

    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Kategorisi</label>
        <input type="text" class="form-control" asp-for="CategoryId" name="CategoryId" placeholder="Kategori Adı">

    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Yılı</label>
        <input type="text" class="form-control" asp-for="Year" name="Year" placeholder="Kategori Adı">

    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Ülkesi</label>
        <input type="text" class="form-control" asp-for="Country" name="Country" placeholder="Kategori Adı">

    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Video Resim</label>
        <input type="text" class="form-control" asp-for="Picture" name="Picture" placeholder="Kategori Adı">

    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Film Videosu</label>
        <input type="text" class="form-control" asp-for="Film" name="Film" placeholder="Kategori Adı">

    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Aktörler</label>
        <input type="text" class="form-control" asp-for="Actors" name="Actors" placeholder="Kategori Adı">

    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Yönetmen</label>
        <input type="text" class="form-control" asp-for="Director" name="Director" placeholder="Kategori Adı">

    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Fragman</label>
        <input type="text" class="form-control" asp-for="Teaser" name="Teaser" placeholder="Kategori Adı">

    </div>
  
   
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

FilmProjesi/Views/Videos/Index.cshtml
@model List<EntityLayer.Concrete.Videos>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Index</h1>
<a class="btn btn-warning" asp-action="Create">Yeni Kayıt</a>
<div class="row">
    <div class="col-md-12">
        <div class="white_shd full margin_bottom_30">
            <div class="full graph_head">
                <div class="heading1 margin_0">
                    <h2>Kategoriler</h2>
                </div>
            </div>
            <div class="table_section padding_infor_info">
                <div class="table-responsive-sm">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>Film Adı</th>
                                <th>Kategorisi</th>
                                <th>Yılı</th>
                                <th>Video Resim</th>
                                <th>Düzeltme</th>
                                <th>Silme</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Title</td>
                                    <td>@item.CategoryId</td>
                                    <td>@item.Year</td>
                                    <td>@item.Picture</td>
                                    <td><a class="btn btn-success" asp-action="Edit" asp-route-id="@item.VideoId">Düzelt</a></td>
                                    <td><a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.VideoId">Silme</a></td>
                                </tr>
                            }


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


</div>